kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: s2ZTG34T3zHukivQTQ3kC88OD+c71BqTKrbfILi67LM=
      - identity: {}
